CREATE TABLE [dm_aou].[dbo].[healthpro-wq] (
  [rid] bigint not null identity primary key,
	[PMI ID] VARCHAR(64) NULL, 
	[Biobank ID] VARCHAR(64) NULL, 
	[Last Name] VARCHAR(256) NULL, 
	[First Name] VARCHAR(256) NULL, 
	[Date of Birth] DATE NULL, 
	[Language] VARCHAR(2) NULL, 
	[General Consent Status] VARCHAR(2) NULL, 
	[General Consent Date] DATE NULL, 
	[EHR Consent Status] VARCHAR(2) NULL, 
	[EHR Consent Date] DATE NULL, 
	[CABoR Consent Status] VARCHAR(2) NULL, 
	[CABoR Consent Date] DATE NULL, 
	[Withdrawal Status] VARCHAR(2) NULL, 
	[Withdrawal Date] DATE NULL, 
	[Street Address] varchar(128) NULL, 
	[City] VARCHAR(128) NULL, 
	[State] VARCHAR(128) NULL, 
	[ZIP] VARCHAR(32) NULL, 
	[Email] VARCHAR(256) NULL, 
	[Phone] VARCHAR(32) NULL, 
	[Sex] VARCHAR(2) NULL, 
	[Gender Identity] VARCHAR(32) NULL, 
	[Sexual Orientation] VARCHAR(32) NULL, 
	[Race/Ethnicity] VARCHAR(32) NULL, 
	[Education] VARCHAR(128) NULL, 
	[Income] VARCHAR(128) NULL, 
	[Required PPI Surveys Complete] VARCHAR(2) NULL, 
	[Completed Surveys] VARCHAR(2) NULL, 
	[Basics PPI Survey Complete] VARCHAR(2) NULL, 
	[Basics PPI Survey Completion Date] DATE NULL, 
	[Health PPI Survey Complete] VARCHAR(2) NULL, 
	[Health PPI Survey Completion Date] DATE NULL, 
	[Lifestyle PPI Survey Complete] VARCHAR(2) NULL, 
	[Lifestyle PPI Survey Completion Date] DATE NULL, 
	[Hist PPI Survey Complete] VARCHAR(2) NULL, 
	[Hist PPI Survey Completion Date] DATE NULL, 
	[Meds PPI Survey Complete] VARCHAR(2) NULL, 
	[Meds PPI Survey Completion Date] DATE NULL, 
	[Family PPI Survey Complete] VARCHAR(2) NULL, 
	[Family PPI Survey Completion Date] DATE NULL, 
	[Access PPI Survey Complete] VARCHAR(2) NULL, 
	[Access PPI Survey Completion Date] DATE NULL, 
	[Physical Measurements Status] VARCHAR(2) NULL, 
	[Physical Measurements Completion Date] DATE NULL, 
	[Samples for DNA Received] VARCHAR(2) NULL, 
	[Biospecimens] INT NULL, 
	[8 mL SST Collected] VARCHAR(2) NULL, 
	[8 mL SST Collection Date] DATE NULL, 
	[8 mL PST Collected] VARCHAR(2) NULL, 
	[8 mL PST Collection Date] DATE NULL, 
	[4 mL Na-Hep Collected] VARCHAR(2) NULL, 
	[4 mL Na-Hep Collection Date] DATE NULL, 
	[4 mL EDTA Collected] VARCHAR(2) NULL, 
	[4 mL EDTA Collection Date] DATE NULL, 
	[1st 10 mL EDTA Collected] VARCHAR(2) NULL, 
	[1st 10 mL EDTA Collection Date] DATE NULL, 
	[2nd 10 mL EDTA Collected] VARCHAR(2) NULL, 
	[2nd 10 mL EDTA Collection Date] DATE NULL, 
	[Urine 10 mL Collected] VARCHAR(2) NULL, 
	[Urine 10 mL Collection Date] DATE NULL, 
	[Saliva Collected] VARCHAR(2) NULL, 
	[Saliva Collection Date] DATE NULL
)
